version: '3'
services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: picpay
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
  php:
    container_name: php
    build: docker/php
    ports:
      - 9000:9000
    volumes:
    - ./:/var/www
    - ~/.composer:/root/.composer
    depends_on:
      - db
